### ISSUE TITLE
Add support for custom command names

### ISSUE THREAD

**Issue by Blayung** [Blayung/no-peeking#2]
Currently the mod only obfuscates /l, /login and /register. Maybe I'll implement it some day.

**Comment by themg95** [comment]
Hi! I've come across your mod from Modtoberfest and I would like to add this feature. This will obviously require a config library and I think we can discuss what can be used. Imo, owo-config would be the best option.

**Comment by Blayung** [comment]
@themg95 Honestly, I'd prefer to have mod menu + cloth config + auto config + toml4j.
